name: alouette_ui_shared
description: Shared UI components for Alouette applications
version: 1.0.0

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  alouette_lib_trans:
    path: ../alouette-lib-trans
  alouette_lib_tts:
    path: ../alouette-lib-tts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
