name: alouette_ui_shared
description: Shared UI components, themes, and service management for Alouette applications
version: 1.0.0

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  # Service interfaces from functional libraries
  alouette_lib_trans:
    path: ../alouette-lib-trans
  alouette_lib_tts:
    path: ../alouette-lib-tts
  # Persistent storage for configuration and preferences
  shared_preferences: ^2.2.2
  # Path provider for file operations
  path_provider: ^2.1.1
  # Meta annotations for better code analysis
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
