name: alouette_lib_tts
description: A multi-platform TTS library supporting Edge TTS and Flutter TTS
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  meta: ^1.9.0
  path: ^1.8.3

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  test: ^1.25.15
  path_provider_platform_interface: ^2.1.1

flutter: