name: alouette_app_tts
description: "Alouette TTS Application - Specialized text-to-speech functionality using unified architecture."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Alouette libraries - only TTS and UI libraries needed
  alouette_lib_tts:
    path: ../alouette_lib_tts
  alouette_ui:
    path: ../alouette_ui
  country_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/alouette_rounded.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/alouette_rounded.png"
  windows:
    generate: true
    image_path: "assets/icons/alouette_rounded.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/alouette_rounded.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/alouette_rounded.png"
